apiVersion: v1
kind: Secret
metadata:
    name: django-settings
type: Opaque
stringData:
    # Django settings
    DEBUG: "False"
    ALLOWED_HOSTS: "*" # For better security, set this to your deployment's domain. Comma separated.
    DJANGO_SECRET_KEY: ""
    SIGNUPS_ENABLED: "False"

    # Redis configuration (if you use the default Kubernetes config, this will work)
    REDIS_CACHE_LOCATION: "redis://redis.default.svc.cluster.local/0"
    CELERY_BROKER_URL: "redis://redis.default.svc.cluster.local/1"

    # PostgreSQL settings
    DB_NAME: ""
    DB_USER: ""
    DB_PASSWORD: ""
    DB_HOST: ""

    # Email settings
    EMAIL_HOST_USER: ""
    EMAIL_HOST_PASSWORD: ""
    EMAIL_HOST: ""
    SERVER_EMAIL: "Shynet <noreply@shynet.example.com>"
